apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base


images:
  - name: gke-nginx-demo
    newName: us-central1-docker.pkg.dev/your-project-id/your-artifact-repo-name/gke-nginx-demo
    newTag: placeholder-tag