apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

images:
- name: gke-nginx-demo
  newName: us-central1-docker.pkg.dev/gke-demo-haowei/gke-nginx-demo/gke-nginx-demo
  newTag: ${COMMIT_SHA}

patches:
- path: ingress-patch.yaml
