name: Trigger Cloud Build on Push

on:
  push:
    branches:
      - main

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloud Build
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Call Cloud Build API
        run: |
          gcloud builds triggers run gke-nginx-demo-trigger \
            --project=gke-demo-haowei \
            --branch=main